import Head from "next/head";
import { BiCheck, BiUserPlus, BiX } from "react-icons/bi";
import Form from "../components/Form";
import Table from "../components/Table";
import { useSelector, useDispatch } from "react-redux";
import { toggleChangeAction, deleteAction } from "../redux/reducer";
import { deleteUser, getUsers } from "../lib/helpers";
import { useQueryClient } from "@tanstack/react-query";

export default function Home() {
  const visible = useSelector((state) => state.app.client.toggleForm);
  const deleteId = useSelector((state) => state.app.client.deleteId);
  const queryClient = useQueryClient();

  const dispatch = useDispatch();

  const handler = () => {
    dispatch(toggleChangeAction());
  };
  const cancelHandler = async () => {
    console.log("canceled")
    await dispatch(deleteAction(null))
  };

  const deleteHandler = async () => {
    if (deleteId) {
      await deleteUser(deleteId);
      await queryClient.prefetchQuery(["users"], getUsers);
      await dispatch(deleteAction(null))
    }
  };

  return (
    <section>
      <Head>
        <title>CRUD Application</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="py-5">
        <h1 className="text-xl md:text-5xl text-center font-bold py-10">
          Employee Management
        </h1>

        <div className="container mx-auto flex justify-between py-5 border-b">
          <div className="left flex gap-3 ">
            <button
              onClick={handler}
              className="flex bg-indigo-500 text-white px-4 py-3 border rounded-md hover:bg-gray-50 hover:border-indigo-500 hover:text-indigo-500"
            >
              Add Employee
              <span className="px-1">
                <BiUserPlus size={23} />
              </span>
            </button>
          </div>
          {deleteId ?  DeleteComponent({ deleteHandler, cancelHandler }) : <></>}
        </div>

        {visible ? <Form /> : <></>}

        <div className="container mx-auto">
          <Table />
        </div>
      </main>
    </section>
  );
}

function DeleteComponent({ deleteHandler, cancelHandler }) {
  return (
    <div className="flex gap-5">
      <button>Are you sure?</button>
      <button
        onClick={deleteHandler}
        className="flex bg-red-500 text-white px-5 py-2 border rounded-md hover:bg-red-400 hover:border-red-600 hover:text-gray-500"
      >
        Yes{" "}
        <span className="px-1">
          {" "}
          <BiX color="rgb(255 255 255)" size={25} />{" "}
        </span>
      </button>
      <button
        onClick={cancelHandler}
        className="flex bg-blue-500 text-white px-5 py-2 border rounded-md hover:bg-blue-400 hover:border-blue-600 hover:text-gray-500"
      >
        No{" "}
        <span className="px-1">
          {" "}
          <BiCheck color="rgb(255 255 255)" size={25} />{" "}
        </span>{" "}
      </button>
    </div>
  );
}
